logger:
  name: "REGRID"
  path: "./logs"

environment_directory:
  target_dir: "/Users/soo._.yonee/Downloads/"
  # target_dir: "./OUTPUT/OPER/OUTPUT/DATA/SAT/GK2/GEMS/L2"
  # target_dir: "./OPER/OUTPUT/DATA/SAT/GK2/GEMS/L2"
  intermediate_dir: "./OUTPUT/L3/hourly/"
  save_dir: "./OUTPUT/L3/"

input_param:
  NO2:
    binning: "ORI"
    variables: ["ColumnAmountNO2"]

grid_param:
#  lon_min: 70 115
#  lon_max: 145 132
#  lat_min: -6 32
#  lat_max: 48 43
  lon_min: 80
  lon_max: 146
  lat_min: -6
  lat_max: 46
  grid_size: 0.05

subgrid_param:
  sublon_min: 120
  sublon_max: 132
  sublat_min: 30
  sublat_max: 44
  subgrid_size: 0.05 

alg_param:
  cf_thresh: 0.3
  sza_thresh: 70
  vza_thresh: 70
  regrid_alg: "tessellation" # "tessellation" or "idw"