logger:
  name: "REGRID"
  path: "./logs"

environment_directory:
#  target_dir: "D:/RStudio/GEMS_L3_avg/06"
#  target_dir: "./OUTPUT/OPER/OUTPUT/DATA/SAT/GK2/GEMS/L2"
  target_dir: "OUTPUT/DATA/SAT/GK2/GEMS/L2"
  intermediate_dir: "OUTPUT/L3/hourly"
  save_dir: "OUTPUT/L3"

input_param:
  NO2:
    binning: "ORI"
    variables: ["ColumnAmountNO2"]

grid:
  ea:
    x0: 70.0
    x1: 145.0
    dx: 0.1
    y0: 48.0
    y1: -6.0
    dy: -0.1
  kr:
    x0: 115.0
    x1: 132.0
    dx: 0.05
    y0: 43.0
    y1: 32.0
    dy: -0.05

alg_param:
  cf_thresh: 0.3
  sza_thresh: 70
  vza_thresh: 70
  regrid_alg: "idw" # "tessellation" or "idw"
  qf_usage: True # "True" or "False"
  radius: 0.1
  p: 2

